// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/justcy/uc/notificator/pkg/endpoint"
	pb "github.com/justcy/uc/notificator/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	sendSms   grpc.Handler
	checkSms  grpc.Handler
	sendEmail grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.NotificatorServer {
	return &grpcServer{
		checkSms:  makeCheckSmsHandler(endpoints, options["CheckSms"]),
		sendEmail: makeSendEmailHandler(endpoints, options["SendEmail"]),
		sendSms:   makeSendSmsHandler(endpoints, options["SendSms"]),
	}
}
